#!/bin/bash
# given a path to a .gv file, create a .ps
# file and open

fname="${1%.*}"
dot -Tps ${fname}.gv -o ${fname}.ps
if hash xdg-open 2>/dev/null; then
  # linux
  xdg-open ${fname}.ps
else
  # macos
  open ${fname}.ps
fi
